[build]
  base = "/"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Run audits for the homepage
    audits = [
      { path = "/" }
    ]
    # Give more time for dynamic content to load
    output_path = "lighthouse.html"